/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AttendanceCheckInPost200Response
 */
export interface AttendanceCheckInPost200Response {
    /**
     * 
     * @type {DtoCheckInResponse}
     * @memberof AttendanceCheckInPost200Response
     */
    'data'?: DtoCheckInResponse;
    /**
     * 
     * @type {string}
     * @memberof AttendanceCheckInPost200Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttendanceCheckInPost200Response
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface AttendanceGet200Response
 */
export interface AttendanceGet200Response {
    /**
     * 
     * @type {DtoGetAttendancesResponse}
     * @memberof AttendanceGet200Response
     */
    'data'?: DtoGetAttendancesResponse;
    /**
     * 
     * @type {string}
     * @memberof AttendanceGet200Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttendanceGet200Response
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface AuthGoogleCallbackGet201Response
 */
export interface AuthGoogleCallbackGet201Response {
    /**
     * 
     * @type {DtoTokenResponse}
     * @memberof AuthGoogleCallbackGet201Response
     */
    'data'?: DtoTokenResponse;
    /**
     * 
     * @type {string}
     * @memberof AuthGoogleCallbackGet201Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthGoogleCallbackGet201Response
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface AuthRegisterPost201Response
 */
export interface AuthRegisterPost201Response {
    /**
     * 
     * @type {DtoRegisteredUserResponse}
     * @memberof AuthRegisterPost201Response
     */
    'data'?: DtoRegisteredUserResponse;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterPost201Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthRegisterPost201Response
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface BranchGet201Response
 */
export interface BranchGet201Response {
    /**
     * 
     * @type {ModelBranch}
     * @memberof BranchGet201Response
     */
    'data'?: ModelBranch;
    /**
     * 
     * @type {string}
     * @memberof BranchGet201Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof BranchGet201Response
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface CompanyGet200Response
 */
export interface CompanyGet200Response {
    /**
     * 
     * @type {DtoGetUserCompaniesResponse}
     * @memberof CompanyGet200Response
     */
    'data'?: DtoGetUserCompaniesResponse;
    /**
     * 
     * @type {string}
     * @memberof CompanyGet200Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyGet200Response
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface CompanyPost201Response
 */
export interface CompanyPost201Response {
    /**
     * 
     * @type {ModelCompany}
     * @memberof CompanyPost201Response
     */
    'data'?: ModelCompany;
    /**
     * 
     * @type {string}
     * @memberof CompanyPost201Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyPost201Response
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface DtoAddEmployeeRequest
 */
export interface DtoAddEmployeeRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeRequest
     */
    'branch_name': string;
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeRequest
     */
    'company_name': string;
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeRequest
     */
    'position': string;
}
/**
 * 
 * @export
 * @interface DtoAddEmployeeResponse
 */
export interface DtoAddEmployeeResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeResponse
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeResponse
     */
    'position'?: string;
}
/**
 * 
 * @export
 * @interface DtoCheckInRequest
 */
export interface DtoCheckInRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInRequest
     */
    'location': string;
}
/**
 * 
 * @export
 * @interface DtoCheckInResponse
 */
export interface DtoCheckInResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInResponse
     */
    'check_in'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInResponse
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInResponse
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInResponse
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInResponse
     */
    'user_id'?: string;
}
/**
 * 
 * @export
 * @interface DtoCreateBranchRequest
 */
export interface DtoCreateBranchRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoCreateBranchRequest
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateBranchRequest
     */
    'branch_name': string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateBranchRequest
     */
    'company_name': string;
}
/**
 * 
 * @export
 * @interface DtoCreateCompanyRequest
 */
export interface DtoCreateCompanyRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoCreateCompanyRequest
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateCompanyRequest
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface DtoCreateQrRequest
 */
export interface DtoCreateQrRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoCreateQrRequest
     */
    'user_id': string;
}
/**
 * 
 * @export
 * @interface DtoCreateQrResponse
 */
export interface DtoCreateQrResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoCreateQrResponse
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateQrResponse
     */
    'expires_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateQrResponse
     */
    'id'?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof DtoCreateQrResponse
     */
    'qr_code'?: Array<number>;
}
/**
 * 
 * @export
 * @interface DtoGetAttendancesResponse
 */
export interface DtoGetAttendancesResponse {
    /**
     * 
     * @type {Array<ModelAttendance>}
     * @memberof DtoGetAttendancesResponse
     */
    'attendances'?: Array<ModelAttendance>;
    /**
     * 
     * @type {string}
     * @memberof DtoGetAttendancesResponse
     */
    'user_id'?: string;
}
/**
 * 
 * @export
 * @interface DtoGetUserCompaniesResponse
 */
export interface DtoGetUserCompaniesResponse {
    /**
     * 
     * @type {Array<ModelCompany>}
     * @memberof DtoGetUserCompaniesResponse
     */
    'company'?: Array<ModelCompany>;
}
/**
 * 
 * @export
 * @interface DtoLoginRequest
 */
export interface DtoLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoLoginRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof DtoLoginRequest
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface DtoRegisterRequest
 */
export interface DtoRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoRegisterRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof DtoRegisterRequest
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof DtoRegisterRequest
     */
    'username': string;
}
/**
 * 
 * @export
 * @interface DtoRegisteredUserResponse
 */
export interface DtoRegisteredUserResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoRegisteredUserResponse
     */
    'email'?: string;
    /**
     * 
     * @type {DtoTokenResponse}
     * @memberof DtoRegisteredUserResponse
     */
    'token'?: DtoTokenResponse;
    /**
     * 
     * @type {string}
     * @memberof DtoRegisteredUserResponse
     */
    'username'?: string;
}
/**
 * 
 * @export
 * @interface DtoTokenResponse
 */
export interface DtoTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoTokenResponse
     */
    'access_token'?: string;
    /**
     * 
     * @type {number}
     * @memberof DtoTokenResponse
     */
    'expires_in'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DtoTokenResponse
     */
    'is_onboarded'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DtoTokenResponse
     */
    'token_type'?: string;
}
/**
 * 
 * @export
 * @interface EmployeePost200Response
 */
export interface EmployeePost200Response {
    /**
     * 
     * @type {DtoAddEmployeeResponse}
     * @memberof EmployeePost200Response
     */
    'data'?: DtoAddEmployeeResponse;
    /**
     * 
     * @type {string}
     * @memberof EmployeePost200Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof EmployeePost200Response
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface MeGet200Response
 */
export interface MeGet200Response {
    /**
     * 
     * @type {ModelUser}
     * @memberof MeGet200Response
     */
    'data'?: ModelUser;
    /**
     * 
     * @type {string}
     * @memberof MeGet200Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof MeGet200Response
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface ModelAttendance
 */
export interface ModelAttendance {
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    'check_in'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    'check_out'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    'location'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    'updated_at'?: string;
    /**
     * 
     * @type {Array<ModelUser>}
     * @memberof ModelAttendance
     */
    'users'?: Array<ModelUser>;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    'uuid'?: string;
}
/**
 * 
 * @export
 * @interface ModelBranch
 */
export interface ModelBranch {
    /**
     * 
     * @type {string}
     * @memberof ModelBranch
     */
    'address'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelBranch
     */
    'company_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelBranch
     */
    'created_at'?: string;
    /**
     * 
     * @type {Array<ModelEmployee>}
     * @memberof ModelBranch
     */
    'employees'?: Array<ModelEmployee>;
    /**
     * 
     * @type {string}
     * @memberof ModelBranch
     */
    'name'?: string;
    /**
     * 
     * @type {Array<ModelRole>}
     * @memberof ModelBranch
     */
    'roles'?: Array<ModelRole>;
    /**
     * 
     * @type {string}
     * @memberof ModelBranch
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelBranch
     */
    'uuid'?: string;
    /**
     * 
     * @type {ModelWorkSchedule}
     * @memberof ModelBranch
     */
    'work_schedule'?: ModelWorkSchedule;
}
/**
 * 
 * @export
 * @interface ModelCompany
 */
export interface ModelCompany {
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    'address'?: string;
    /**
     * 
     * @type {Array<ModelBranch>}
     * @memberof ModelCompany
     */
    'branches'?: Array<ModelBranch>;
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    'name'?: string;
    /**
     * 
     * @type {ModelCompanyOption}
     * @memberof ModelCompany
     */
    'options'?: ModelCompanyOption;
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    'owner_email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    'picture'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    'uuid'?: string;
    /**
     * 
     * @type {ModelWorkSchedule}
     * @memberof ModelCompany
     */
    'work_schedule'?: ModelWorkSchedule;
}
/**
 * 
 * @export
 * @interface ModelCompanyOption
 */
export interface ModelCompanyOption {
    /**
     * 
     * @type {string}
     * @memberof ModelCompanyOption
     */
    'check_in_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCompanyOption
     */
    'check_out_time'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelCompanyOption
     */
    'company_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelCompanyOption
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCompanyOption
     */
    'updated_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelCompanyOption
     */
    'use_checkout'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelCompanyOption
     */
    'uuid'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelCompanyOption
     */
    'workingHours'?: number;
}
/**
 * 
 * @export
 * @interface ModelEmployee
 */
export interface ModelEmployee {
    /**
     * 
     * @type {number}
     * @memberof ModelEmployee
     */
    'branch_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelEmployee
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelEmployee
     */
    'employee_email'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelEmployee
     */
    'pending'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelEmployee
     */
    'position'?: string;
    /**
     * 
     * @type {ModelSalary}
     * @memberof ModelEmployee
     */
    'salary'?: ModelSalary;
    /**
     * 
     * @type {string}
     * @memberof ModelEmployee
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelEmployee
     */
    'uuid'?: string;
    /**
     * 
     * @type {ModelWorkSchedule}
     * @memberof ModelEmployee
     */
    'work_schedule'?: ModelWorkSchedule;
}
/**
 * 
 * @export
 * @interface ModelLog
 */
export interface ModelLog {
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    'action'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    'executionTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    'method'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    'path'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    'remoteAddr'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelLog
     */
    'size'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelLog
     */
    'status'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    'userAgent'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    'uuid'?: string;
}
/**
 * 
 * @export
 * @interface ModelPermission
 */
export interface ModelPermission {
    /**
     * get,post,put/patch,delete
     * @type {string}
     * @memberof ModelPermission
     */
    'action'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelPermission
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelPermission
     */
    'resource'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelPermission
     */
    'updated_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelPermission
     */
    'user_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelPermission
     */
    'uuid'?: string;
}
/**
 * 
 * @export
 * @interface ModelQRCode
 */
export interface ModelQRCode {
    /**
     * 
     * @type {string}
     * @memberof ModelQRCode
     */
    'code'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelQRCode
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelQRCode
     */
    'expires_at'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelQRCode
     */
    'is_used'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelQRCode
     */
    'updated_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelQRCode
     */
    'user_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelQRCode
     */
    'uuid'?: string;
}
/**
 * 
 * @export
 * @interface ModelRole
 */
export interface ModelRole {
    /**
     * 
     * @type {number}
     * @memberof ModelRole
     */
    'branch_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelRole
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelRole
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelRole
     */
    'updated_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelRole
     */
    'user_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelRole
     */
    'uuid'?: string;
}
/**
 * 
 * @export
 * @interface ModelSalary
 */
export interface ModelSalary {
    /**
     * 
     * @type {string}
     * @memberof ModelSalary
     */
    'created_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelSalary
     */
    'currentEarnings'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelSalary
     */
    'employeeEmail'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelSalary
     */
    'hourly'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelSalary
     */
    'monthly'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelSalary
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelSalary
     */
    'uuid'?: string;
}
/**
 * 
 * @export
 * @interface ModelSession
 */
export interface ModelSession {
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    'expires_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    'ip_address'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelSession
     */
    'is_revoked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    'refresh_token'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    'user_agent'?: string;
    /**
     * 
     * @type {Array<ModelUser>}
     * @memberof ModelSession
     */
    'users'?: Array<ModelUser>;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    'uuid'?: string;
}
/**
 * 
 * @export
 * @interface ModelUser
 */
export interface ModelUser {
    /**
     * 
     * @type {Array<ModelAttendance>}
     * @memberof ModelUser
     */
    'attendances'?: Array<ModelAttendance>;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    'auth_provider'?: string;
    /**
     * 
     * @type {Array<ModelCompany>}
     * @memberof ModelUser
     */
    'company'?: Array<ModelCompany>;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    'email'?: string;
    /**
     * 
     * @type {ModelEmployee}
     * @memberof ModelUser
     */
    'employee'?: ModelEmployee;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUser
     */
    'is_email_verified'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUser
     */
    'is_on_boarded'?: boolean;
    /**
     * 
     * @type {ModelLog}
     * @memberof ModelUser
     */
    'log'?: ModelLog;
    /**
     * 
     * @type {Array<ModelPermission>}
     * @memberof ModelUser
     */
    'permissions'?: Array<ModelPermission>;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    'picture'?: string;
    /**
     * 
     * @type {ModelQRCode}
     * @memberof ModelUser
     */
    'qrcode'?: ModelQRCode;
    /**
     * admin, owner, employee
     * @type {string}
     * @memberof ModelUser
     */
    'role'?: string;
    /**
     * 
     * @type {Array<ModelSession>}
     * @memberof ModelUser
     */
    'sessions'?: Array<ModelSession>;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    'username'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    'uuid'?: string;
}
/**
 * 
 * @export
 * @interface ModelWorkSchedule
 */
export interface ModelWorkSchedule {
    /**
     * 
     * @type {number}
     * @memberof ModelWorkSchedule
     */
    'branch_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelWorkSchedule
     */
    'company_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    'created_at'?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelWorkSchedule
     */
    'employee_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    'end_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    'start_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    'updated_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    'uuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    'working_day'?: string;
}
/**
 * 
 * @export
 * @interface QrcodeGet200Response
 */
export interface QrcodeGet200Response {
    /**
     * 
     * @type {DtoCreateQrResponse}
     * @memberof QrcodeGet200Response
     */
    'data'?: DtoCreateQrResponse;
    /**
     * 
     * @type {string}
     * @memberof QrcodeGet200Response
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof QrcodeGet200Response
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface TypesErrorResponse
 */
export interface TypesErrorResponse {
    /**
     * 
     * @type {object}
     * @memberof TypesErrorResponse
     */
    'error'?: object;
    /**
     * 
     * @type {string}
     * @memberof TypesErrorResponse
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof TypesErrorResponse
     */
    'status'?: number;
}
/**
 * 
 * @export
 * @interface TypesResponse
 */
export interface TypesResponse {
    /**
     * 
     * @type {object}
     * @memberof TypesResponse
     */
    'data'?: object;
    /**
     * 
     * @type {string}
     * @memberof TypesResponse
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof TypesResponse
     */
    'status'?: number;
}

/**
 * AttendanceApi - axios parameter creator
 * @export
 */
export const AttendanceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * daily checkin user, use qrcode to check in
         * @summary check in user
         * @param {DtoCheckInRequest} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attendanceCheckInPost: async (request: DtoCheckInRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('attendanceCheckInPost', 'request', request)
            const localVarPath = `/attendance/check-in`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * get specific user attendances
         * @summary Get User Attendances
         * @param {string} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attendanceGet: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('attendanceGet', 'userId', userId)
            const localVarPath = `/attendance`
                .replace(`{${"userId"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AttendanceApi - functional programming interface
 * @export
 */
export const AttendanceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AttendanceApiAxiosParamCreator(configuration)
    return {
        /**
         * daily checkin user, use qrcode to check in
         * @summary check in user
         * @param {DtoCheckInRequest} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async attendanceCheckInPost(request: DtoCheckInRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AttendanceCheckInPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.attendanceCheckInPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendanceApi.attendanceCheckInPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * get specific user attendances
         * @summary Get User Attendances
         * @param {string} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async attendanceGet(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AttendanceGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.attendanceGet(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AttendanceApi.attendanceGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AttendanceApi - factory interface
 * @export
 */
export const AttendanceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AttendanceApiFp(configuration)
    return {
        /**
         * daily checkin user, use qrcode to check in
         * @summary check in user
         * @param {DtoCheckInRequest} request request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attendanceCheckInPost(request: DtoCheckInRequest, options?: RawAxiosRequestConfig): AxiosPromise<AttendanceCheckInPost200Response> {
            return localVarFp.attendanceCheckInPost(request, options).then((request) => request(axios, basePath));
        },
        /**
         * get specific user attendances
         * @summary Get User Attendances
         * @param {string} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attendanceGet(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<AttendanceGet200Response> {
            return localVarFp.attendanceGet(userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AttendanceApi - object-oriented interface
 * @export
 * @class AttendanceApi
 * @extends {BaseAPI}
 */
export class AttendanceApi extends BaseAPI {
    /**
     * daily checkin user, use qrcode to check in
     * @summary check in user
     * @param {DtoCheckInRequest} request request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttendanceApi
     */
    public attendanceCheckInPost(request: DtoCheckInRequest, options?: RawAxiosRequestConfig) {
        return AttendanceApiFp(this.configuration).attendanceCheckInPost(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * get specific user attendances
     * @summary Get User Attendances
     * @param {string} userId userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AttendanceApi
     */
    public attendanceGet(userId: string, options?: RawAxiosRequestConfig) {
        return AttendanceApiFp(this.configuration).attendanceGet(userId, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Handles the Google OAuth callback, exchanges the code for a token, and creates/updates a user.
         * @summary Google OAuth callback handler
         * @param {string} state State for OAuth validation
         * @param {string} code Authorization code received from Google
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGoogleCallbackGet: async (state: string, code: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'state' is not null or undefined
            assertParamExists('authGoogleCallbackGet', 'state', state)
            // verify required parameter 'code' is not null or undefined
            assertParamExists('authGoogleCallbackGet', 'code', code)
            const localVarPath = `/auth/google/callback`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (state !== undefined) {
                localVarQueryParameter['state'] = state;
            }

            if (code !== undefined) {
                localVarQueryParameter['code'] = code;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Initiates Google OAuth 2.0 login by generating a state and redirecting to Google\'s authorization URL
         * @summary Redirects user to Google\'s OAuth 2.0 authentication page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGoogleLoginGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/google/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * login as user
         * @summary login as user
         * @param {DtoLoginRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost: async (request: DtoLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('authLoginPost', 'request', request)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * this endpoint used for logout user and remove user refresh token and accesstoken
         * @summary Logout User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Register new user
         * @summary Register as user
         * @param {DtoRegisterRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost: async (request: DtoRegisterRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('authRegisterPost', 'request', request)
            const localVarPath = `/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Renew Access Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenRenewGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/token/renew`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * Handles the Google OAuth callback, exchanges the code for a token, and creates/updates a user.
         * @summary Google OAuth callback handler
         * @param {string} state State for OAuth validation
         * @param {string} code Authorization code received from Google
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authGoogleCallbackGet(state: string, code: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthGoogleCallbackGet201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authGoogleCallbackGet(state, code, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authGoogleCallbackGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Initiates Google OAuth 2.0 login by generating a state and redirecting to Google\'s authorization URL
         * @summary Redirects user to Google\'s OAuth 2.0 authentication page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authGoogleLoginGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authGoogleLoginGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authGoogleLoginGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * login as user
         * @summary login as user
         * @param {DtoLoginRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLoginPost(request: DtoLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthGoogleCallbackGet201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLoginPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * this endpoint used for logout user and remove user refresh token and accesstoken
         * @summary Logout User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLogoutPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthGoogleCallbackGet201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLogoutPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLogoutPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Register new user
         * @summary Register as user
         * @param {DtoRegisterRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authRegisterPost(request: DtoRegisterRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthRegisterPost201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authRegisterPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Renew Access Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authTokenRenewGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthGoogleCallbackGet201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authTokenRenewGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authTokenRenewGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * Handles the Google OAuth callback, exchanges the code for a token, and creates/updates a user.
         * @summary Google OAuth callback handler
         * @param {string} state State for OAuth validation
         * @param {string} code Authorization code received from Google
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGoogleCallbackGet(state: string, code: string, options?: RawAxiosRequestConfig): AxiosPromise<AuthGoogleCallbackGet201Response> {
            return localVarFp.authGoogleCallbackGet(state, code, options).then((request) => request(axios, basePath));
        },
        /**
         * Initiates Google OAuth 2.0 login by generating a state and redirecting to Google\'s authorization URL
         * @summary Redirects user to Google\'s OAuth 2.0 authentication page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authGoogleLoginGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authGoogleLoginGet(options).then((request) => request(axios, basePath));
        },
        /**
         * login as user
         * @summary login as user
         * @param {DtoLoginRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost(request: DtoLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthGoogleCallbackGet201Response> {
            return localVarFp.authLoginPost(request, options).then((request) => request(axios, basePath));
        },
        /**
         * this endpoint used for logout user and remove user refresh token and accesstoken
         * @summary Logout User
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost(options?: RawAxiosRequestConfig): AxiosPromise<AuthGoogleCallbackGet201Response> {
            return localVarFp.authLogoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * Register new user
         * @summary Register as user
         * @param {DtoRegisterRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost(request: DtoRegisterRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthRegisterPost201Response> {
            return localVarFp.authRegisterPost(request, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Renew Access Token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTokenRenewGet(options?: RawAxiosRequestConfig): AxiosPromise<AuthGoogleCallbackGet201Response> {
            return localVarFp.authTokenRenewGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * Handles the Google OAuth callback, exchanges the code for a token, and creates/updates a user.
     * @summary Google OAuth callback handler
     * @param {string} state State for OAuth validation
     * @param {string} code Authorization code received from Google
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authGoogleCallbackGet(state: string, code: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authGoogleCallbackGet(state, code, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Initiates Google OAuth 2.0 login by generating a state and redirecting to Google\'s authorization URL
     * @summary Redirects user to Google\'s OAuth 2.0 authentication page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authGoogleLoginGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authGoogleLoginGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * login as user
     * @summary login as user
     * @param {DtoLoginRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authLoginPost(request: DtoLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLoginPost(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * this endpoint used for logout user and remove user refresh token and accesstoken
     * @summary Logout User
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authLogoutPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLogoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Register new user
     * @summary Register as user
     * @param {DtoRegisterRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authRegisterPost(request: DtoRegisterRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authRegisterPost(request, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Renew Access Token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public authTokenRenewGet(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authTokenRenewGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * BranchApi - axios parameter creator
 * @export
 */
export const BranchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * getting company branches that only owner can get [owner only]
         * @summary [owner only] get company branches
         * @param {string} companyName company name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchGet: async (companyName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyName' is not null or undefined
            assertParamExists('branchGet', 'companyName', companyName)
            const localVarPath = `/branch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (companyName !== undefined) {
                localVarQueryParameter['company_name'] = companyName;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * creating new branch using company name that only owner can create
         * @summary [owner only] create new branch using company name
         * @param {DtoCreateBranchRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchPost: async (request: DtoCreateBranchRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('branchPost', 'request', request)
            const localVarPath = `/branch`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BranchApi - functional programming interface
 * @export
 */
export const BranchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BranchApiAxiosParamCreator(configuration)
    return {
        /**
         * getting company branches that only owner can get [owner only]
         * @summary [owner only] get company branches
         * @param {string} companyName company name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async branchGet(companyName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BranchGet201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.branchGet(companyName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchApi.branchGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * creating new branch using company name that only owner can create
         * @summary [owner only] create new branch using company name
         * @param {DtoCreateBranchRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async branchPost(request: DtoCreateBranchRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BranchGet201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.branchPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BranchApi.branchPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BranchApi - factory interface
 * @export
 */
export const BranchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BranchApiFp(configuration)
    return {
        /**
         * getting company branches that only owner can get [owner only]
         * @summary [owner only] get company branches
         * @param {string} companyName company name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchGet(companyName: string, options?: RawAxiosRequestConfig): AxiosPromise<BranchGet201Response> {
            return localVarFp.branchGet(companyName, options).then((request) => request(axios, basePath));
        },
        /**
         * creating new branch using company name that only owner can create
         * @summary [owner only] create new branch using company name
         * @param {DtoCreateBranchRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        branchPost(request: DtoCreateBranchRequest, options?: RawAxiosRequestConfig): AxiosPromise<BranchGet201Response> {
            return localVarFp.branchPost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BranchApi - object-oriented interface
 * @export
 * @class BranchApi
 * @extends {BaseAPI}
 */
export class BranchApi extends BaseAPI {
    /**
     * getting company branches that only owner can get [owner only]
     * @summary [owner only] get company branches
     * @param {string} companyName company name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BranchApi
     */
    public branchGet(companyName: string, options?: RawAxiosRequestConfig) {
        return BranchApiFp(this.configuration).branchGet(companyName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * creating new branch using company name that only owner can create
     * @summary [owner only] create new branch using company name
     * @param {DtoCreateBranchRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BranchApi
     */
    public branchPost(request: DtoCreateBranchRequest, options?: RawAxiosRequestConfig) {
        return BranchApiFp(this.configuration).branchPost(request, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CompanyApi - axios parameter creator
 * @export
 */
export const CompanyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * get all companies of owner
         * @summary get owner companies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/company`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * creating new company
         * @summary Create new company
         * @param {DtoCreateCompanyRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyPost: async (request: DtoCreateCompanyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('companyPost', 'request', request)
            const localVarPath = `/company`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CompanyApi - functional programming interface
 * @export
 */
export const CompanyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CompanyApiAxiosParamCreator(configuration)
    return {
        /**
         * get all companies of owner
         * @summary get owner companies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async companyGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CompanyGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.companyGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CompanyApi.companyGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * creating new company
         * @summary Create new company
         * @param {DtoCreateCompanyRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async companyPost(request: DtoCreateCompanyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CompanyPost201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.companyPost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CompanyApi.companyPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CompanyApi - factory interface
 * @export
 */
export const CompanyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CompanyApiFp(configuration)
    return {
        /**
         * get all companies of owner
         * @summary get owner companies
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyGet(options?: RawAxiosRequestConfig): AxiosPromise<CompanyGet200Response> {
            return localVarFp.companyGet(options).then((request) => request(axios, basePath));
        },
        /**
         * creating new company
         * @summary Create new company
         * @param {DtoCreateCompanyRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        companyPost(request: DtoCreateCompanyRequest, options?: RawAxiosRequestConfig): AxiosPromise<CompanyPost201Response> {
            return localVarFp.companyPost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CompanyApi - object-oriented interface
 * @export
 * @class CompanyApi
 * @extends {BaseAPI}
 */
export class CompanyApi extends BaseAPI {
    /**
     * get all companies of owner
     * @summary get owner companies
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompanyApi
     */
    public companyGet(options?: RawAxiosRequestConfig) {
        return CompanyApiFp(this.configuration).companyGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * creating new company
     * @summary Create new company
     * @param {DtoCreateCompanyRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CompanyApi
     */
    public companyPost(request: DtoCreateCompanyRequest, options?: RawAxiosRequestConfig) {
        return CompanyApiFp(this.configuration).companyPost(request, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * EmployeeApi - axios parameter creator
 * @export
 */
export const EmployeeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * invite user to join company
         * @summary Add Employee
         * @param {DtoAddEmployeeRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        employeePost: async (request: DtoAddEmployeeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('employeePost', 'request', request)
            const localVarPath = `/employee`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EmployeeApi - functional programming interface
 * @export
 */
export const EmployeeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EmployeeApiAxiosParamCreator(configuration)
    return {
        /**
         * invite user to join company
         * @summary Add Employee
         * @param {DtoAddEmployeeRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async employeePost(request: DtoAddEmployeeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EmployeePost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.employeePost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EmployeeApi.employeePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EmployeeApi - factory interface
 * @export
 */
export const EmployeeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EmployeeApiFp(configuration)
    return {
        /**
         * invite user to join company
         * @summary Add Employee
         * @param {DtoAddEmployeeRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        employeePost(request: DtoAddEmployeeRequest, options?: RawAxiosRequestConfig): AxiosPromise<EmployeePost200Response> {
            return localVarFp.employeePost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EmployeeApi - object-oriented interface
 * @export
 * @class EmployeeApi
 * @extends {BaseAPI}
 */
export class EmployeeApi extends BaseAPI {
    /**
     * invite user to join company
     * @summary Add Employee
     * @param {DtoAddEmployeeRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EmployeeApi
     */
    public employeePost(request: DtoAddEmployeeRequest, options?: RawAxiosRequestConfig) {
        return EmployeeApiFp(this.configuration).employeePost(request, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MeApi - axios parameter creator
 * @export
 */
export const MeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * get all informations about myself
         * @summary get myself informations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MeApi - functional programming interface
 * @export
 */
export const MeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MeApiAxiosParamCreator(configuration)
    return {
        /**
         * get all informations about myself
         * @summary get myself informations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MeGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeApi.meGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MeApi - factory interface
 * @export
 */
export const MeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MeApiFp(configuration)
    return {
        /**
         * get all informations about myself
         * @summary get myself informations
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meGet(options?: RawAxiosRequestConfig): AxiosPromise<MeGet200Response> {
            return localVarFp.meGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MeApi - object-oriented interface
 * @export
 * @class MeApi
 * @extends {BaseAPI}
 */
export class MeApi extends BaseAPI {
    /**
     * get all informations about myself
     * @summary get myself informations
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeApi
     */
    public meGet(options?: RawAxiosRequestConfig) {
        return MeApiFp(this.configuration).meGet(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * QrCodeApi - axios parameter creator
 * @export
 */
export const QrCodeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * daily checkin user
         * @summary check in user
         * @param {string} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        qrcodeGet: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('qrcodeGet', 'userId', userId)
            const localVarPath = `/qrcode`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (userId !== undefined) {
                localVarQueryParameter['userId'] = userId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * manually re-generating user qrcode
         * @summary re-generate user qrcode
         * @param {DtoCreateQrRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        qrcodePost: async (request: DtoCreateQrRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'request' is not null or undefined
            assertParamExists('qrcodePost', 'request', request)
            const localVarPath = `/qrcode`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QrCodeApi - functional programming interface
 * @export
 */
export const QrCodeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QrCodeApiAxiosParamCreator(configuration)
    return {
        /**
         * daily checkin user
         * @summary check in user
         * @param {string} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async qrcodeGet(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QrcodeGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.qrcodeGet(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QrCodeApi.qrcodeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * manually re-generating user qrcode
         * @summary re-generate user qrcode
         * @param {DtoCreateQrRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async qrcodePost(request: DtoCreateQrRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QrcodeGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.qrcodePost(request, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QrCodeApi.qrcodePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QrCodeApi - factory interface
 * @export
 */
export const QrCodeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QrCodeApiFp(configuration)
    return {
        /**
         * daily checkin user
         * @summary check in user
         * @param {string} userId userId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        qrcodeGet(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<QrcodeGet200Response> {
            return localVarFp.qrcodeGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * manually re-generating user qrcode
         * @summary re-generate user qrcode
         * @param {DtoCreateQrRequest} request Request body
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        qrcodePost(request: DtoCreateQrRequest, options?: RawAxiosRequestConfig): AxiosPromise<QrcodeGet200Response> {
            return localVarFp.qrcodePost(request, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QrCodeApi - object-oriented interface
 * @export
 * @class QrCodeApi
 * @extends {BaseAPI}
 */
export class QrCodeApi extends BaseAPI {
    /**
     * daily checkin user
     * @summary check in user
     * @param {string} userId userId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QrCodeApi
     */
    public qrcodeGet(userId: string, options?: RawAxiosRequestConfig) {
        return QrCodeApiFp(this.configuration).qrcodeGet(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * manually re-generating user qrcode
     * @summary re-generate user qrcode
     * @param {DtoCreateQrRequest} request Request body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QrCodeApi
     */
    public qrcodePost(request: DtoCreateQrRequest, options?: RawAxiosRequestConfig) {
        return QrCodeApiFp(this.configuration).qrcodePost(request, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * getting all users information
         * @summary Get All Users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * getting specific user information
         * @summary Get User by UserId
         * @param {string} userID User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUserIDGet: async (userID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userID' is not null or undefined
            assertParamExists('usersUserIDGet', 'userID', userID)
            const localVarPath = `/users/{userID}`
                .replace(`{${"userID"}}`, encodeURIComponent(String(userID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * getting all users information
         * @summary Get All Users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MeGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * getting specific user information
         * @summary Get User by UserId
         * @param {string} userID User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersUserIDGet(userID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MeGet200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersUserIDGet(userID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersUserIDGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * getting all users information
         * @summary Get All Users
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersGet(options?: RawAxiosRequestConfig): AxiosPromise<MeGet200Response> {
            return localVarFp.usersGet(options).then((request) => request(axios, basePath));
        },
        /**
         * getting specific user information
         * @summary Get User by UserId
         * @param {string} userID User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersUserIDGet(userID: string, options?: RawAxiosRequestConfig): AxiosPromise<MeGet200Response> {
            return localVarFp.usersUserIDGet(userID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * getting all users information
     * @summary Get All Users
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public usersGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * getting specific user information
     * @summary Get User by UserId
     * @param {string} userID User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public usersUserIDGet(userID: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersUserIDGet(userID, options).then((request) => request(this.axios, this.basePath));
    }
}



