/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AttendanceCheckInPost200Response,
  AttendanceGet200Response,
  DtoCheckInRequest,
  TypesErrorResponse,
} from '../models/index';
import {
    AttendanceCheckInPost200ResponseFromJSON,
    AttendanceCheckInPost200ResponseToJSON,
    AttendanceGet200ResponseFromJSON,
    AttendanceGet200ResponseToJSON,
    DtoCheckInRequestFromJSON,
    DtoCheckInRequestToJSON,
    TypesErrorResponseFromJSON,
    TypesErrorResponseToJSON,
} from '../models/index';

export interface AttendanceCheckInPostRequest {
    request: DtoCheckInRequest;
}

export interface AttendanceGetRequest {
    userId: string;
}

/**
 * 
 */
export class AttendanceApi extends runtime.BaseAPI {

    /**
     * daily checkin user, use qrcode to check in
     * check in user
     */
    async attendanceCheckInPostRaw(requestParameters: AttendanceCheckInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AttendanceCheckInPost200Response>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling attendanceCheckInPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/attendance/check-in`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DtoCheckInRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttendanceCheckInPost200ResponseFromJSON(jsonValue));
    }

    /**
     * daily checkin user, use qrcode to check in
     * check in user
     */
    async attendanceCheckInPost(requestParameters: AttendanceCheckInPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AttendanceCheckInPost200Response> {
        const response = await this.attendanceCheckInPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * get specific user attendances
     * Get User Attendances
     */
    async attendanceGetRaw(requestParameters: AttendanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AttendanceGet200Response>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling attendanceGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/attendance`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AttendanceGet200ResponseFromJSON(jsonValue));
    }

    /**
     * get specific user attendances
     * Get User Attendances
     */
    async attendanceGet(requestParameters: AttendanceGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AttendanceGet200Response> {
        const response = await this.attendanceGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
