/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthGoogleCallbackGet201Response,
  AuthRegisterPost201Response,
  DtoLoginRequest,
  DtoRegisterRequest,
  TypesErrorResponse,
} from '../models/index';
import {
    AuthGoogleCallbackGet201ResponseFromJSON,
    AuthGoogleCallbackGet201ResponseToJSON,
    AuthRegisterPost201ResponseFromJSON,
    AuthRegisterPost201ResponseToJSON,
    DtoLoginRequestFromJSON,
    DtoLoginRequestToJSON,
    DtoRegisterRequestFromJSON,
    DtoRegisterRequestToJSON,
    TypesErrorResponseFromJSON,
    TypesErrorResponseToJSON,
} from '../models/index';

export interface AuthGoogleCallbackGetRequest {
    state: string;
    code: string;
}

export interface AuthLoginPostRequest {
    request: DtoLoginRequest;
}

export interface AuthRegisterPostRequest {
    request: DtoRegisterRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Handles the Google OAuth callback, exchanges the code for a token, and creates/updates a user.
     * Google OAuth callback handler
     */
    async authGoogleCallbackGetRaw(requestParameters: AuthGoogleCallbackGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthGoogleCallbackGet201Response>> {
        if (requestParameters['state'] == null) {
            throw new runtime.RequiredError(
                'state',
                'Required parameter "state" was null or undefined when calling authGoogleCallbackGet().'
            );
        }

        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling authGoogleCallbackGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['state'] != null) {
            queryParameters['state'] = requestParameters['state'];
        }

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/google/callback`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthGoogleCallbackGet201ResponseFromJSON(jsonValue));
    }

    /**
     * Handles the Google OAuth callback, exchanges the code for a token, and creates/updates a user.
     * Google OAuth callback handler
     */
    async authGoogleCallbackGet(requestParameters: AuthGoogleCallbackGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthGoogleCallbackGet201Response> {
        const response = await this.authGoogleCallbackGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Initiates Google OAuth 2.0 login by generating a state and redirecting to Google\'s authorization URL
     * Redirects user to Google\'s OAuth 2.0 authentication page
     */
    async authGoogleLoginGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/google/login`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Initiates Google OAuth 2.0 login by generating a state and redirecting to Google\'s authorization URL
     * Redirects user to Google\'s OAuth 2.0 authentication page
     */
    async authGoogleLoginGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authGoogleLoginGetRaw(initOverrides);
    }

    /**
     * login as user
     * login as user
     */
    async authLoginPostRaw(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthGoogleCallbackGet201Response>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling authLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DtoLoginRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthGoogleCallbackGet201ResponseFromJSON(jsonValue));
    }

    /**
     * login as user
     * login as user
     */
    async authLoginPost(requestParameters: AuthLoginPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthGoogleCallbackGet201Response> {
        const response = await this.authLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * this endpoint used for logout user and remove user refresh token and accesstoken
     * Logout User
     */
    async authLogoutPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthGoogleCallbackGet201Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/logout`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthGoogleCallbackGet201ResponseFromJSON(jsonValue));
    }

    /**
     * this endpoint used for logout user and remove user refresh token and accesstoken
     * Logout User
     */
    async authLogoutPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthGoogleCallbackGet201Response> {
        const response = await this.authLogoutPostRaw(initOverrides);
        return await response.value();
    }

    /**
     * Register new user
     * Register as user
     */
    async authRegisterPostRaw(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthRegisterPost201Response>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling authRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DtoRegisterRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthRegisterPost201ResponseFromJSON(jsonValue));
    }

    /**
     * Register new user
     * Register as user
     */
    async authRegisterPost(requestParameters: AuthRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthRegisterPost201Response> {
        const response = await this.authRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Renew Access Token
     */
    async authTokenRenewGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthGoogleCallbackGet201Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/token/renew`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthGoogleCallbackGet201ResponseFromJSON(jsonValue));
    }

    /**
     * Renew Access Token
     */
    async authTokenRenewGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthGoogleCallbackGet201Response> {
        const response = await this.authTokenRenewGetRaw(initOverrides);
        return await response.value();
    }

}
