/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BranchGet201Response,
  DtoCreateBranchRequest,
  TypesErrorResponse,
} from '../models/index';
import {
    BranchGet201ResponseFromJSON,
    BranchGet201ResponseToJSON,
    DtoCreateBranchRequestFromJSON,
    DtoCreateBranchRequestToJSON,
    TypesErrorResponseFromJSON,
    TypesErrorResponseToJSON,
} from '../models/index';

export interface BranchGetRequest {
    companyName: string;
}

export interface BranchPostRequest {
    request: DtoCreateBranchRequest;
}

/**
 * 
 */
export class BranchApi extends runtime.BaseAPI {

    /**
     * getting company branches that only owner can get [owner only]
     * [owner only] get company branches
     */
    async branchGetRaw(requestParameters: BranchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BranchGet201Response>> {
        if (requestParameters['companyName'] == null) {
            throw new runtime.RequiredError(
                'companyName',
                'Required parameter "companyName" was null or undefined when calling branchGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['companyName'] != null) {
            queryParameters['company_name'] = requestParameters['companyName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/branch`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BranchGet201ResponseFromJSON(jsonValue));
    }

    /**
     * getting company branches that only owner can get [owner only]
     * [owner only] get company branches
     */
    async branchGet(requestParameters: BranchGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BranchGet201Response> {
        const response = await this.branchGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * creating new branch using company name that only owner can create
     * [owner only] create new branch using company name
     */
    async branchPostRaw(requestParameters: BranchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BranchGet201Response>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling branchPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/branch`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DtoCreateBranchRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BranchGet201ResponseFromJSON(jsonValue));
    }

    /**
     * creating new branch using company name that only owner can create
     * [owner only] create new branch using company name
     */
    async branchPost(requestParameters: BranchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BranchGet201Response> {
        const response = await this.branchPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
