/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CompanyGet200Response,
  TypesErrorResponse,
} from '../models/index';
import {
    CompanyGet200ResponseFromJSON,
    CompanyGet200ResponseToJSON,
    TypesErrorResponseFromJSON,
    TypesErrorResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class CompanyApi extends runtime.BaseAPI {

    /**
     * get all companies of owner
     * get owner companies
     */
    async companyGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CompanyGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/company`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CompanyGet200ResponseFromJSON(jsonValue));
    }

    /**
     * get all companies of owner
     * get owner companies
     */
    async companyGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CompanyGet200Response> {
        const response = await this.companyGetRaw(initOverrides);
        return await response.value();
    }

}
