/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DtoAddEmployeeRequest,
  EmployeePost200Response,
  TypesErrorResponse,
} from '../models/index';
import {
    DtoAddEmployeeRequestFromJSON,
    DtoAddEmployeeRequestToJSON,
    EmployeePost200ResponseFromJSON,
    EmployeePost200ResponseToJSON,
    TypesErrorResponseFromJSON,
    TypesErrorResponseToJSON,
} from '../models/index';

export interface EmployeePostRequest {
    request: DtoAddEmployeeRequest;
}

/**
 * 
 */
export class EmployeeApi extends runtime.BaseAPI {

    /**
     * invite user to join company
     * Add Employee
     */
    async employeePostRaw(requestParameters: EmployeePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EmployeePost200Response>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling employeePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/employee`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DtoAddEmployeeRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EmployeePost200ResponseFromJSON(jsonValue));
    }

    /**
     * invite user to join company
     * Add Employee
     */
    async employeePost(requestParameters: EmployeePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EmployeePost200Response> {
        const response = await this.employeePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
