/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MeGet200Response,
  TypesErrorResponse,
} from '../models/index';
import {
    MeGet200ResponseFromJSON,
    MeGet200ResponseToJSON,
    TypesErrorResponseFromJSON,
    TypesErrorResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class MeApi extends runtime.BaseAPI {

    /**
     * get all informations about myself
     * get myself informations
     */
    async meGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeGet200ResponseFromJSON(jsonValue));
    }

    /**
     * get all informations about myself
     * get myself informations
     */
    async meGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeGet200Response> {
        const response = await this.meGetRaw(initOverrides);
        return await response.value();
    }

}
