/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DtoCreateQrRequest,
  QrcodeGet200Response,
  TypesErrorResponse,
} from '../models/index';
import {
    DtoCreateQrRequestFromJSON,
    DtoCreateQrRequestToJSON,
    QrcodeGet200ResponseFromJSON,
    QrcodeGet200ResponseToJSON,
    TypesErrorResponseFromJSON,
    TypesErrorResponseToJSON,
} from '../models/index';

export interface QrcodeGetRequest {
    userId: string;
}

export interface QrcodePostRequest {
    request: DtoCreateQrRequest;
}

/**
 * 
 */
export class QrCodeApi extends runtime.BaseAPI {

    /**
     * daily checkin user
     * check in user
     */
    async qrcodeGetRaw(requestParameters: QrcodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QrcodeGet200Response>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling qrcodeGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userId'] != null) {
            queryParameters['userId'] = requestParameters['userId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/qrcode`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QrcodeGet200ResponseFromJSON(jsonValue));
    }

    /**
     * daily checkin user
     * check in user
     */
    async qrcodeGet(requestParameters: QrcodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QrcodeGet200Response> {
        const response = await this.qrcodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * manually re-generating user qrcode
     * re-generate user qrcode
     */
    async qrcodePostRaw(requestParameters: QrcodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QrcodeGet200Response>> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling qrcodePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/qrcode`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DtoCreateQrRequestToJSON(requestParameters['request']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QrcodeGet200ResponseFromJSON(jsonValue));
    }

    /**
     * manually re-generating user qrcode
     * re-generate user qrcode
     */
    async qrcodePost(requestParameters: QrcodePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QrcodeGet200Response> {
        const response = await this.qrcodePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
