/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MeGet200Response,
  TypesErrorResponse,
} from '../models/index';
import {
    MeGet200ResponseFromJSON,
    MeGet200ResponseToJSON,
    TypesErrorResponseFromJSON,
    TypesErrorResponseToJSON,
} from '../models/index';

export interface UsersUserIDGetRequest {
    userID: string;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * getting all users information
     * Get All Users
     */
    async usersGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeGet200ResponseFromJSON(jsonValue));
    }

    /**
     * getting all users information
     * Get All Users
     */
    async usersGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeGet200Response> {
        const response = await this.usersGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * getting specific user information
     * Get User by UserId
     */
    async usersUserIDGetRaw(requestParameters: UsersUserIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MeGet200Response>> {
        if (requestParameters['userID'] == null) {
            throw new runtime.RequiredError(
                'userID',
                'Required parameter "userID" was null or undefined when calling usersUserIDGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // BearerAuth authentication
        }

        const response = await this.request({
            path: `/users/{userID}`.replace(`{${"userID"}}`, encodeURIComponent(String(requestParameters['userID']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MeGet200ResponseFromJSON(jsonValue));
    }

    /**
     * getting specific user information
     * Get User by UserId
     */
    async usersUserIDGet(requestParameters: UsersUserIDGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MeGet200Response> {
        const response = await this.usersUserIDGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
