/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoCheckInResponse } from './DtoCheckInResponse';
import {
    DtoCheckInResponseFromJSON,
    DtoCheckInResponseFromJSONTyped,
    DtoCheckInResponseToJSON,
    DtoCheckInResponseToJSONTyped,
} from './DtoCheckInResponse';

/**
 * 
 * @export
 * @interface AttendanceCheckInPost200Response
 */
export interface AttendanceCheckInPost200Response {
    /**
     * 
     * @type {DtoCheckInResponse}
     * @memberof AttendanceCheckInPost200Response
     */
    data?: DtoCheckInResponse;
    /**
     * 
     * @type {string}
     * @memberof AttendanceCheckInPost200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof AttendanceCheckInPost200Response
     */
    status?: number;
}

/**
 * Check if a given object implements the AttendanceCheckInPost200Response interface.
 */
export function instanceOfAttendanceCheckInPost200Response(value: object): value is AttendanceCheckInPost200Response {
    return true;
}

export function AttendanceCheckInPost200ResponseFromJSON(json: any): AttendanceCheckInPost200Response {
    return AttendanceCheckInPost200ResponseFromJSONTyped(json, false);
}

export function AttendanceCheckInPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendanceCheckInPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DtoCheckInResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AttendanceCheckInPost200ResponseToJSON(json: any): AttendanceCheckInPost200Response {
    return AttendanceCheckInPost200ResponseToJSONTyped(json, false);
}

export function AttendanceCheckInPost200ResponseToJSONTyped(value?: AttendanceCheckInPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DtoCheckInResponseToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

