/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoGetAttendancesResponse } from './DtoGetAttendancesResponse';
import {
    DtoGetAttendancesResponseFromJSON,
    DtoGetAttendancesResponseFromJSONTyped,
    DtoGetAttendancesResponseToJSON,
    DtoGetAttendancesResponseToJSONTyped,
} from './DtoGetAttendancesResponse';

/**
 * 
 * @export
 * @interface AttendanceGet200Response
 */
export interface AttendanceGet200Response {
    /**
     * 
     * @type {DtoGetAttendancesResponse}
     * @memberof AttendanceGet200Response
     */
    data?: DtoGetAttendancesResponse;
    /**
     * 
     * @type {string}
     * @memberof AttendanceGet200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof AttendanceGet200Response
     */
    status?: number;
}

/**
 * Check if a given object implements the AttendanceGet200Response interface.
 */
export function instanceOfAttendanceGet200Response(value: object): value is AttendanceGet200Response {
    return true;
}

export function AttendanceGet200ResponseFromJSON(json: any): AttendanceGet200Response {
    return AttendanceGet200ResponseFromJSONTyped(json, false);
}

export function AttendanceGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttendanceGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DtoGetAttendancesResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AttendanceGet200ResponseToJSON(json: any): AttendanceGet200Response {
    return AttendanceGet200ResponseToJSONTyped(json, false);
}

export function AttendanceGet200ResponseToJSONTyped(value?: AttendanceGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DtoGetAttendancesResponseToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

