/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoTokenResponse } from './DtoTokenResponse';
import {
    DtoTokenResponseFromJSON,
    DtoTokenResponseFromJSONTyped,
    DtoTokenResponseToJSON,
    DtoTokenResponseToJSONTyped,
} from './DtoTokenResponse';

/**
 * 
 * @export
 * @interface AuthGoogleCallbackGet201Response
 */
export interface AuthGoogleCallbackGet201Response {
    /**
     * 
     * @type {DtoTokenResponse}
     * @memberof AuthGoogleCallbackGet201Response
     */
    data?: DtoTokenResponse;
    /**
     * 
     * @type {string}
     * @memberof AuthGoogleCallbackGet201Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthGoogleCallbackGet201Response
     */
    status?: number;
}

/**
 * Check if a given object implements the AuthGoogleCallbackGet201Response interface.
 */
export function instanceOfAuthGoogleCallbackGet201Response(value: object): value is AuthGoogleCallbackGet201Response {
    return true;
}

export function AuthGoogleCallbackGet201ResponseFromJSON(json: any): AuthGoogleCallbackGet201Response {
    return AuthGoogleCallbackGet201ResponseFromJSONTyped(json, false);
}

export function AuthGoogleCallbackGet201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthGoogleCallbackGet201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DtoTokenResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AuthGoogleCallbackGet201ResponseToJSON(json: any): AuthGoogleCallbackGet201Response {
    return AuthGoogleCallbackGet201ResponseToJSONTyped(json, false);
}

export function AuthGoogleCallbackGet201ResponseToJSONTyped(value?: AuthGoogleCallbackGet201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DtoTokenResponseToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

