/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoRegisteredUserResponse } from './DtoRegisteredUserResponse';
import {
    DtoRegisteredUserResponseFromJSON,
    DtoRegisteredUserResponseFromJSONTyped,
    DtoRegisteredUserResponseToJSON,
    DtoRegisteredUserResponseToJSONTyped,
} from './DtoRegisteredUserResponse';

/**
 * 
 * @export
 * @interface AuthRegisterPost201Response
 */
export interface AuthRegisterPost201Response {
    /**
     * 
     * @type {DtoRegisteredUserResponse}
     * @memberof AuthRegisterPost201Response
     */
    data?: DtoRegisteredUserResponse;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterPost201Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof AuthRegisterPost201Response
     */
    status?: number;
}

/**
 * Check if a given object implements the AuthRegisterPost201Response interface.
 */
export function instanceOfAuthRegisterPost201Response(value: object): value is AuthRegisterPost201Response {
    return true;
}

export function AuthRegisterPost201ResponseFromJSON(json: any): AuthRegisterPost201Response {
    return AuthRegisterPost201ResponseFromJSONTyped(json, false);
}

export function AuthRegisterPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRegisterPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DtoRegisteredUserResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function AuthRegisterPost201ResponseToJSON(json: any): AuthRegisterPost201Response {
    return AuthRegisterPost201ResponseToJSONTyped(json, false);
}

export function AuthRegisterPost201ResponseToJSONTyped(value?: AuthRegisterPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DtoRegisteredUserResponseToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

