/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelBranch } from './ModelBranch';
import {
    ModelBranchFromJSON,
    ModelBranchFromJSONTyped,
    ModelBranchToJSON,
    ModelBranchToJSONTyped,
} from './ModelBranch';

/**
 * 
 * @export
 * @interface BranchGet201Response
 */
export interface BranchGet201Response {
    /**
     * 
     * @type {ModelBranch}
     * @memberof BranchGet201Response
     */
    data?: ModelBranch;
    /**
     * 
     * @type {string}
     * @memberof BranchGet201Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof BranchGet201Response
     */
    status?: number;
}

/**
 * Check if a given object implements the BranchGet201Response interface.
 */
export function instanceOfBranchGet201Response(value: object): value is BranchGet201Response {
    return true;
}

export function BranchGet201ResponseFromJSON(json: any): BranchGet201Response {
    return BranchGet201ResponseFromJSONTyped(json, false);
}

export function BranchGet201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BranchGet201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ModelBranchFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function BranchGet201ResponseToJSON(json: any): BranchGet201Response {
    return BranchGet201ResponseToJSONTyped(json, false);
}

export function BranchGet201ResponseToJSONTyped(value?: BranchGet201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ModelBranchToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

