/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoGetUserCompaniesResponse } from './DtoGetUserCompaniesResponse';
import {
    DtoGetUserCompaniesResponseFromJSON,
    DtoGetUserCompaniesResponseFromJSONTyped,
    DtoGetUserCompaniesResponseToJSON,
    DtoGetUserCompaniesResponseToJSONTyped,
} from './DtoGetUserCompaniesResponse';

/**
 * 
 * @export
 * @interface CompanyGet200Response
 */
export interface CompanyGet200Response {
    /**
     * 
     * @type {DtoGetUserCompaniesResponse}
     * @memberof CompanyGet200Response
     */
    data?: DtoGetUserCompaniesResponse;
    /**
     * 
     * @type {string}
     * @memberof CompanyGet200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof CompanyGet200Response
     */
    status?: number;
}

/**
 * Check if a given object implements the CompanyGet200Response interface.
 */
export function instanceOfCompanyGet200Response(value: object): value is CompanyGet200Response {
    return true;
}

export function CompanyGet200ResponseFromJSON(json: any): CompanyGet200Response {
    return CompanyGet200ResponseFromJSONTyped(json, false);
}

export function CompanyGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DtoGetUserCompaniesResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function CompanyGet200ResponseToJSON(json: any): CompanyGet200Response {
    return CompanyGet200ResponseToJSONTyped(json, false);
}

export function CompanyGet200ResponseToJSONTyped(value?: CompanyGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DtoGetUserCompaniesResponseToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

