/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoAddEmployeeResponse
 */
export interface DtoAddEmployeeResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeResponse
     */
    position?: string;
}

/**
 * Check if a given object implements the DtoAddEmployeeResponse interface.
 */
export function instanceOfDtoAddEmployeeResponse(value: object): value is DtoAddEmployeeResponse {
    return true;
}

export function DtoAddEmployeeResponseFromJSON(json: any): DtoAddEmployeeResponse {
    return DtoAddEmployeeResponseFromJSONTyped(json, false);
}

export function DtoAddEmployeeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoAddEmployeeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function DtoAddEmployeeResponseToJSON(json: any): DtoAddEmployeeResponse {
    return DtoAddEmployeeResponseToJSONTyped(json, false);
}

export function DtoAddEmployeeResponseToJSONTyped(value?: DtoAddEmployeeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'position': value['position'],
    };
}

