/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoAddEmployeeRequest
 */
export interface DtoAddEmployeeRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeRequest
     */
    branchName: string;
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeRequest
     */
    companyName: string;
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof DtoAddEmployeeRequest
     */
    position: string;
}

/**
 * Check if a given object implements the DtoAddEmployeeRequest interface.
 */
export function instanceOfDtoAddEmployeeRequest(value: object): value is DtoAddEmployeeRequest {
    if (!('branchName' in value) || value['branchName'] === undefined) return false;
    if (!('companyName' in value) || value['companyName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    return true;
}

export function DtoAddEmployeeRequestFromJSON(json: any): DtoAddEmployeeRequest {
    return DtoAddEmployeeRequestFromJSONTyped(json, false);
}

export function DtoAddEmployeeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoAddEmployeeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'branchName': json['branch_name'],
        'companyName': json['company_name'],
        'email': json['email'],
        'position': json['position'],
    };
}

export function DtoAddEmployeeRequestToJSON(json: any): DtoAddEmployeeRequest {
    return DtoAddEmployeeRequestToJSONTyped(json, false);
}

export function DtoAddEmployeeRequestToJSONTyped(value?: DtoAddEmployeeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch_name': value['branchName'],
        'company_name': value['companyName'],
        'email': value['email'],
        'position': value['position'],
    };
}

