/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoCreateCompanyRequest
 */
export interface DtoCreateCompanyRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoCreateCompanyRequest
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateCompanyRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the DtoCreateCompanyRequest interface.
 */
export function instanceOfDtoCreateCompanyRequest(value: object): value is DtoCreateCompanyRequest {
    return true;
}

export function DtoCreateCompanyRequestFromJSON(json: any): DtoCreateCompanyRequest {
    return DtoCreateCompanyRequestFromJSONTyped(json, false);
}

export function DtoCreateCompanyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoCreateCompanyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function DtoCreateCompanyRequestToJSON(json: any): DtoCreateCompanyRequest {
    return DtoCreateCompanyRequestToJSONTyped(json, false);
}

export function DtoCreateCompanyRequestToJSONTyped(value?: DtoCreateCompanyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'name': value['name'],
    };
}

