/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoCheckInResponse
 */
export interface DtoCheckInResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInResponse
     */
    checkIn?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInResponse
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInResponse
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInResponse
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInResponse
     */
    userId?: string;
}

/**
 * Check if a given object implements the DtoCheckInResponse interface.
 */
export function instanceOfDtoCheckInResponse(value: object): value is DtoCheckInResponse {
    return true;
}

export function DtoCheckInResponseFromJSON(json: any): DtoCheckInResponse {
    return DtoCheckInResponseFromJSONTyped(json, false);
}

export function DtoCheckInResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoCheckInResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'checkIn': json['check_in'] == null ? undefined : json['check_in'],
        'date': json['date'] == null ? undefined : json['date'],
        'location': json['location'] == null ? undefined : json['location'],
        'status': json['status'] == null ? undefined : json['status'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function DtoCheckInResponseToJSON(json: any): DtoCheckInResponse {
    return DtoCheckInResponseToJSONTyped(json, false);
}

export function DtoCheckInResponseToJSONTyped(value?: DtoCheckInResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'check_in': value['checkIn'],
        'date': value['date'],
        'location': value['location'],
        'status': value['status'],
        'user_id': value['userId'],
    };
}

