/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoCreateQrRequest
 */
export interface DtoCreateQrRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoCreateQrRequest
     */
    userId: string;
}

/**
 * Check if a given object implements the DtoCreateQrRequest interface.
 */
export function instanceOfDtoCreateQrRequest(value: object): value is DtoCreateQrRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function DtoCreateQrRequestFromJSON(json: any): DtoCreateQrRequest {
    return DtoCreateQrRequestFromJSONTyped(json, false);
}

export function DtoCreateQrRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoCreateQrRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
    };
}

export function DtoCreateQrRequestToJSON(json: any): DtoCreateQrRequest {
    return DtoCreateQrRequestToJSONTyped(json, false);
}

export function DtoCreateQrRequestToJSONTyped(value?: DtoCreateQrRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
    };
}

