/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoCheckInRequest
 */
export interface DtoCheckInRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoCheckInRequest
     */
    location: string;
}

/**
 * Check if a given object implements the DtoCheckInRequest interface.
 */
export function instanceOfDtoCheckInRequest(value: object): value is DtoCheckInRequest {
    if (!('location' in value) || value['location'] === undefined) return false;
    return true;
}

export function DtoCheckInRequestFromJSON(json: any): DtoCheckInRequest {
    return DtoCheckInRequestFromJSONTyped(json, false);
}

export function DtoCheckInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoCheckInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'location': json['location'],
    };
}

export function DtoCheckInRequestToJSON(json: any): DtoCheckInRequest {
    return DtoCheckInRequestToJSONTyped(json, false);
}

export function DtoCheckInRequestToJSONTyped(value?: DtoCheckInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'location': value['location'],
    };
}

