/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoCreateBranchRequest
 */
export interface DtoCreateBranchRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoCreateBranchRequest
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateBranchRequest
     */
    branchName: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateBranchRequest
     */
    companyName: string;
}

/**
 * Check if a given object implements the DtoCreateBranchRequest interface.
 */
export function instanceOfDtoCreateBranchRequest(value: object): value is DtoCreateBranchRequest {
    if (!('address' in value) || value['address'] === undefined) return false;
    if (!('branchName' in value) || value['branchName'] === undefined) return false;
    if (!('companyName' in value) || value['companyName'] === undefined) return false;
    return true;
}

export function DtoCreateBranchRequestFromJSON(json: any): DtoCreateBranchRequest {
    return DtoCreateBranchRequestFromJSONTyped(json, false);
}

export function DtoCreateBranchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoCreateBranchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'branchName': json['branch_name'],
        'companyName': json['company_name'],
    };
}

export function DtoCreateBranchRequestToJSON(json: any): DtoCreateBranchRequest {
    return DtoCreateBranchRequestToJSONTyped(json, false);
}

export function DtoCreateBranchRequestToJSONTyped(value?: DtoCreateBranchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'branch_name': value['branchName'],
        'company_name': value['companyName'],
    };
}

