/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoCreateQrResponse
 */
export interface DtoCreateQrResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoCreateQrResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateQrResponse
     */
    expiresAt?: string;
    /**
     * 
     * @type {string}
     * @memberof DtoCreateQrResponse
     */
    id?: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof DtoCreateQrResponse
     */
    qrCode?: Array<number>;
}

/**
 * Check if a given object implements the DtoCreateQrResponse interface.
 */
export function instanceOfDtoCreateQrResponse(value: object): value is DtoCreateQrResponse {
    return true;
}

export function DtoCreateQrResponseFromJSON(json: any): DtoCreateQrResponse {
    return DtoCreateQrResponseFromJSONTyped(json, false);
}

export function DtoCreateQrResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoCreateQrResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'qrCode': json['qr_code'] == null ? undefined : json['qr_code'],
    };
}

export function DtoCreateQrResponseToJSON(json: any): DtoCreateQrResponse {
    return DtoCreateQrResponseToJSONTyped(json, false);
}

export function DtoCreateQrResponseToJSONTyped(value?: DtoCreateQrResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'expires_at': value['expiresAt'],
        'id': value['id'],
        'qr_code': value['qrCode'],
    };
}

