/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelCompany } from './ModelCompany';
import {
    ModelCompanyFromJSON,
    ModelCompanyFromJSONTyped,
    ModelCompanyToJSON,
    ModelCompanyToJSONTyped,
} from './ModelCompany';

/**
 * 
 * @export
 * @interface DtoGetUserCompaniesResponse
 */
export interface DtoGetUserCompaniesResponse {
    /**
     * 
     * @type {Array<ModelCompany>}
     * @memberof DtoGetUserCompaniesResponse
     */
    company?: Array<ModelCompany>;
}

/**
 * Check if a given object implements the DtoGetUserCompaniesResponse interface.
 */
export function instanceOfDtoGetUserCompaniesResponse(value: object): value is DtoGetUserCompaniesResponse {
    return true;
}

export function DtoGetUserCompaniesResponseFromJSON(json: any): DtoGetUserCompaniesResponse {
    return DtoGetUserCompaniesResponseFromJSONTyped(json, false);
}

export function DtoGetUserCompaniesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoGetUserCompaniesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'company': json['company'] == null ? undefined : ((json['company'] as Array<any>).map(ModelCompanyFromJSON)),
    };
}

export function DtoGetUserCompaniesResponseToJSON(json: any): DtoGetUserCompaniesResponse {
    return DtoGetUserCompaniesResponseToJSONTyped(json, false);
}

export function DtoGetUserCompaniesResponseToJSONTyped(value?: DtoGetUserCompaniesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'] == null ? undefined : ((value['company'] as Array<any>).map(ModelCompanyToJSON)),
    };
}

