/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelAttendance } from './ModelAttendance';
import {
    ModelAttendanceFromJSON,
    ModelAttendanceFromJSONTyped,
    ModelAttendanceToJSON,
    ModelAttendanceToJSONTyped,
} from './ModelAttendance';

/**
 * 
 * @export
 * @interface DtoGetAttendancesResponse
 */
export interface DtoGetAttendancesResponse {
    /**
     * 
     * @type {Array<ModelAttendance>}
     * @memberof DtoGetAttendancesResponse
     */
    attendances?: Array<ModelAttendance>;
    /**
     * 
     * @type {string}
     * @memberof DtoGetAttendancesResponse
     */
    userId?: string;
}

/**
 * Check if a given object implements the DtoGetAttendancesResponse interface.
 */
export function instanceOfDtoGetAttendancesResponse(value: object): value is DtoGetAttendancesResponse {
    return true;
}

export function DtoGetAttendancesResponseFromJSON(json: any): DtoGetAttendancesResponse {
    return DtoGetAttendancesResponseFromJSONTyped(json, false);
}

export function DtoGetAttendancesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoGetAttendancesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'attendances': json['attendances'] == null ? undefined : ((json['attendances'] as Array<any>).map(ModelAttendanceFromJSON)),
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function DtoGetAttendancesResponseToJSON(json: any): DtoGetAttendancesResponse {
    return DtoGetAttendancesResponseToJSONTyped(json, false);
}

export function DtoGetAttendancesResponseToJSONTyped(value?: DtoGetAttendancesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attendances': value['attendances'] == null ? undefined : ((value['attendances'] as Array<any>).map(ModelAttendanceToJSON)),
        'user_id': value['userId'],
    };
}

