/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoLoginRequest
 */
export interface DtoLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoLoginRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof DtoLoginRequest
     */
    password: string;
}

/**
 * Check if a given object implements the DtoLoginRequest interface.
 */
export function instanceOfDtoLoginRequest(value: object): value is DtoLoginRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function DtoLoginRequestFromJSON(json: any): DtoLoginRequest {
    return DtoLoginRequestFromJSONTyped(json, false);
}

export function DtoLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function DtoLoginRequestToJSON(json: any): DtoLoginRequest {
    return DtoLoginRequestToJSONTyped(json, false);
}

export function DtoLoginRequestToJSONTyped(value?: DtoLoginRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

