/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoRegisterRequest
 */
export interface DtoRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof DtoRegisterRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof DtoRegisterRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof DtoRegisterRequest
     */
    username: string;
}

/**
 * Check if a given object implements the DtoRegisterRequest interface.
 */
export function instanceOfDtoRegisterRequest(value: object): value is DtoRegisterRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function DtoRegisterRequestFromJSON(json: any): DtoRegisterRequest {
    return DtoRegisterRequestFromJSONTyped(json, false);
}

export function DtoRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'username': json['username'],
    };
}

export function DtoRegisterRequestToJSON(json: any): DtoRegisterRequest {
    return DtoRegisterRequestToJSONTyped(json, false);
}

export function DtoRegisterRequestToJSONTyped(value?: DtoRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'username': value['username'],
    };
}

