/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoTokenResponse } from './DtoTokenResponse';
import {
    DtoTokenResponseFromJSON,
    DtoTokenResponseFromJSONTyped,
    DtoTokenResponseToJSON,
    DtoTokenResponseToJSONTyped,
} from './DtoTokenResponse';

/**
 * 
 * @export
 * @interface DtoRegisteredUserResponse
 */
export interface DtoRegisteredUserResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoRegisteredUserResponse
     */
    email?: string;
    /**
     * 
     * @type {DtoTokenResponse}
     * @memberof DtoRegisteredUserResponse
     */
    token?: DtoTokenResponse;
    /**
     * 
     * @type {string}
     * @memberof DtoRegisteredUserResponse
     */
    username?: string;
}

/**
 * Check if a given object implements the DtoRegisteredUserResponse interface.
 */
export function instanceOfDtoRegisteredUserResponse(value: object): value is DtoRegisteredUserResponse {
    return true;
}

export function DtoRegisteredUserResponseFromJSON(json: any): DtoRegisteredUserResponse {
    return DtoRegisteredUserResponseFromJSONTyped(json, false);
}

export function DtoRegisteredUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoRegisteredUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'token': json['token'] == null ? undefined : DtoTokenResponseFromJSON(json['token']),
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function DtoRegisteredUserResponseToJSON(json: any): DtoRegisteredUserResponse {
    return DtoRegisteredUserResponseToJSONTyped(json, false);
}

export function DtoRegisteredUserResponseToJSONTyped(value?: DtoRegisteredUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'token': DtoTokenResponseToJSON(value['token']),
        'username': value['username'],
    };
}

