/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DtoTokenResponse
 */
export interface DtoTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof DtoTokenResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {number}
     * @memberof DtoTokenResponse
     */
    expiresIn?: number;
    /**
     * 
     * @type {string}
     * @memberof DtoTokenResponse
     */
    tokenType?: string;
}

/**
 * Check if a given object implements the DtoTokenResponse interface.
 */
export function instanceOfDtoTokenResponse(value: object): value is DtoTokenResponse {
    return true;
}

export function DtoTokenResponseFromJSON(json: any): DtoTokenResponse {
    return DtoTokenResponseFromJSONTyped(json, false);
}

export function DtoTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DtoTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'] == null ? undefined : json['access_token'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
    };
}

export function DtoTokenResponseToJSON(json: any): DtoTokenResponse {
    return DtoTokenResponseToJSONTyped(json, false);
}

export function DtoTokenResponseToJSONTyped(value?: DtoTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'expires_in': value['expiresIn'],
        'token_type': value['tokenType'],
    };
}

