/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoAddEmployeeResponse } from './DtoAddEmployeeResponse';
import {
    DtoAddEmployeeResponseFromJSON,
    DtoAddEmployeeResponseFromJSONTyped,
    DtoAddEmployeeResponseToJSON,
    DtoAddEmployeeResponseToJSONTyped,
} from './DtoAddEmployeeResponse';

/**
 * 
 * @export
 * @interface EmployeePost200Response
 */
export interface EmployeePost200Response {
    /**
     * 
     * @type {DtoAddEmployeeResponse}
     * @memberof EmployeePost200Response
     */
    data?: DtoAddEmployeeResponse;
    /**
     * 
     * @type {string}
     * @memberof EmployeePost200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof EmployeePost200Response
     */
    status?: number;
}

/**
 * Check if a given object implements the EmployeePost200Response interface.
 */
export function instanceOfEmployeePost200Response(value: object): value is EmployeePost200Response {
    return true;
}

export function EmployeePost200ResponseFromJSON(json: any): EmployeePost200Response {
    return EmployeePost200ResponseFromJSONTyped(json, false);
}

export function EmployeePost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeePost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DtoAddEmployeeResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function EmployeePost200ResponseToJSON(json: any): EmployeePost200Response {
    return EmployeePost200ResponseToJSONTyped(json, false);
}

export function EmployeePost200ResponseToJSONTyped(value?: EmployeePost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DtoAddEmployeeResponseToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

