/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelUser } from './ModelUser';
import {
    ModelUserFromJSON,
    ModelUserFromJSONTyped,
    ModelUserToJSON,
    ModelUserToJSONTyped,
} from './ModelUser';

/**
 * 
 * @export
 * @interface MeGet200Response
 */
export interface MeGet200Response {
    /**
     * 
     * @type {ModelUser}
     * @memberof MeGet200Response
     */
    data?: ModelUser;
    /**
     * 
     * @type {string}
     * @memberof MeGet200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof MeGet200Response
     */
    status?: number;
}

/**
 * Check if a given object implements the MeGet200Response interface.
 */
export function instanceOfMeGet200Response(value: object): value is MeGet200Response {
    return true;
}

export function MeGet200ResponseFromJSON(json: any): MeGet200Response {
    return MeGet200ResponseFromJSONTyped(json, false);
}

export function MeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ModelUserFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function MeGet200ResponseToJSON(json: any): MeGet200Response {
    return MeGet200ResponseToJSONTyped(json, false);
}

export function MeGet200ResponseToJSONTyped(value?: MeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ModelUserToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

