/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelSalary
 */
export interface ModelSalary {
    /**
     * 
     * @type {string}
     * @memberof ModelSalary
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelSalary
     */
    currentEarnings?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelSalary
     */
    employeeEmail?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelSalary
     */
    hourly?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelSalary
     */
    monthly?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelSalary
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelSalary
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ModelSalary interface.
 */
export function instanceOfModelSalary(value: object): value is ModelSalary {
    return true;
}

export function ModelSalaryFromJSON(json: any): ModelSalary {
    return ModelSalaryFromJSONTyped(json, false);
}

export function ModelSalaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelSalary {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'currentEarnings': json['currentEarnings'] == null ? undefined : json['currentEarnings'],
        'employeeEmail': json['employeeEmail'] == null ? undefined : json['employeeEmail'],
        'hourly': json['hourly'] == null ? undefined : json['hourly'],
        'monthly': json['monthly'] == null ? undefined : json['monthly'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ModelSalaryToJSON(json: any): ModelSalary {
    return ModelSalaryToJSONTyped(json, false);
}

export function ModelSalaryToJSONTyped(value?: ModelSalary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'currentEarnings': value['currentEarnings'],
        'employeeEmail': value['employeeEmail'],
        'hourly': value['hourly'],
        'monthly': value['monthly'],
        'updated_at': value['updatedAt'],
        'uuid': value['uuid'],
    };
}

