/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelPermission
 */
export interface ModelPermission {
    /**
     * get,post,put/patch,delete
     * @type {string}
     * @memberof ModelPermission
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelPermission
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelPermission
     */
    resource?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelPermission
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelPermission
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelPermission
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ModelPermission interface.
 */
export function instanceOfModelPermission(value: object): value is ModelPermission {
    return true;
}

export function ModelPermissionFromJSON(json: any): ModelPermission {
    return ModelPermissionFromJSONTyped(json, false);
}

export function ModelPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelPermission {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'resource': json['resource'] == null ? undefined : json['resource'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ModelPermissionToJSON(json: any): ModelPermission {
    return ModelPermissionToJSONTyped(json, false);
}

export function ModelPermissionToJSONTyped(value?: ModelPermission | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'created_at': value['createdAt'],
        'resource': value['resource'],
        'updated_at': value['updatedAt'],
        'user_id': value['userId'],
        'uuid': value['uuid'],
    };
}

