/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelQRCode
 */
export interface ModelQRCode {
    /**
     * 
     * @type {string}
     * @memberof ModelQRCode
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelQRCode
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelQRCode
     */
    expiresAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelQRCode
     */
    isUsed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelQRCode
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelQRCode
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelQRCode
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ModelQRCode interface.
 */
export function instanceOfModelQRCode(value: object): value is ModelQRCode {
    return true;
}

export function ModelQRCodeFromJSON(json: any): ModelQRCode {
    return ModelQRCodeFromJSONTyped(json, false);
}

export function ModelQRCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelQRCode {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'isUsed': json['is_used'] == null ? undefined : json['is_used'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ModelQRCodeToJSON(json: any): ModelQRCode {
    return ModelQRCodeToJSONTyped(json, false);
}

export function ModelQRCodeToJSONTyped(value?: ModelQRCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'created_at': value['createdAt'],
        'expires_at': value['expiresAt'],
        'is_used': value['isUsed'],
        'updated_at': value['updatedAt'],
        'user_id': value['userId'],
        'uuid': value['uuid'],
    };
}

