/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelSalary } from './ModelSalary';
import {
    ModelSalaryFromJSON,
    ModelSalaryFromJSONTyped,
    ModelSalaryToJSON,
    ModelSalaryToJSONTyped,
} from './ModelSalary';
import type { ModelWorkSchedule } from './ModelWorkSchedule';
import {
    ModelWorkScheduleFromJSON,
    ModelWorkScheduleFromJSONTyped,
    ModelWorkScheduleToJSON,
    ModelWorkScheduleToJSONTyped,
} from './ModelWorkSchedule';

/**
 * 
 * @export
 * @interface ModelEmployee
 */
export interface ModelEmployee {
    /**
     * 
     * @type {number}
     * @memberof ModelEmployee
     */
    branchId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelEmployee
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelEmployee
     */
    employeeEmail?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelEmployee
     */
    pending?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelEmployee
     */
    position?: string;
    /**
     * 
     * @type {ModelSalary}
     * @memberof ModelEmployee
     */
    salary?: ModelSalary;
    /**
     * 
     * @type {string}
     * @memberof ModelEmployee
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelEmployee
     */
    uuid?: string;
    /**
     * 
     * @type {ModelWorkSchedule}
     * @memberof ModelEmployee
     */
    workSchedule?: ModelWorkSchedule;
}

/**
 * Check if a given object implements the ModelEmployee interface.
 */
export function instanceOfModelEmployee(value: object): value is ModelEmployee {
    return true;
}

export function ModelEmployeeFromJSON(json: any): ModelEmployee {
    return ModelEmployeeFromJSONTyped(json, false);
}

export function ModelEmployeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelEmployee {
    if (json == null) {
        return json;
    }
    return {
        
        'branchId': json['branch_id'] == null ? undefined : json['branch_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'employeeEmail': json['employee_email'] == null ? undefined : json['employee_email'],
        'pending': json['pending'] == null ? undefined : json['pending'],
        'position': json['position'] == null ? undefined : json['position'],
        'salary': json['salary'] == null ? undefined : ModelSalaryFromJSON(json['salary']),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'workSchedule': json['work_schedule'] == null ? undefined : ModelWorkScheduleFromJSON(json['work_schedule']),
    };
}

export function ModelEmployeeToJSON(json: any): ModelEmployee {
    return ModelEmployeeToJSONTyped(json, false);
}

export function ModelEmployeeToJSONTyped(value?: ModelEmployee | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch_id': value['branchId'],
        'created_at': value['createdAt'],
        'employee_email': value['employeeEmail'],
        'pending': value['pending'],
        'position': value['position'],
        'salary': ModelSalaryToJSON(value['salary']),
        'updated_at': value['updatedAt'],
        'uuid': value['uuid'],
        'work_schedule': ModelWorkScheduleToJSON(value['workSchedule']),
    };
}

