/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelRole } from './ModelRole';
import {
    ModelRoleFromJSON,
    ModelRoleFromJSONTyped,
    ModelRoleToJSON,
    ModelRoleToJSONTyped,
} from './ModelRole';
import type { ModelEmployee } from './ModelEmployee';
import {
    ModelEmployeeFromJSON,
    ModelEmployeeFromJSONTyped,
    ModelEmployeeToJSON,
    ModelEmployeeToJSONTyped,
} from './ModelEmployee';
import type { ModelWorkSchedule } from './ModelWorkSchedule';
import {
    ModelWorkScheduleFromJSON,
    ModelWorkScheduleFromJSONTyped,
    ModelWorkScheduleToJSON,
    ModelWorkScheduleToJSONTyped,
} from './ModelWorkSchedule';

/**
 * 
 * @export
 * @interface ModelBranch
 */
export interface ModelBranch {
    /**
     * 
     * @type {string}
     * @memberof ModelBranch
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelBranch
     */
    companyId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelBranch
     */
    createdAt?: string;
    /**
     * 
     * @type {Array<ModelEmployee>}
     * @memberof ModelBranch
     */
    employees?: Array<ModelEmployee>;
    /**
     * 
     * @type {string}
     * @memberof ModelBranch
     */
    name?: string;
    /**
     * 
     * @type {Array<ModelRole>}
     * @memberof ModelBranch
     */
    roles?: Array<ModelRole>;
    /**
     * 
     * @type {string}
     * @memberof ModelBranch
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelBranch
     */
    uuid?: string;
    /**
     * 
     * @type {ModelWorkSchedule}
     * @memberof ModelBranch
     */
    workSchedule?: ModelWorkSchedule;
}

/**
 * Check if a given object implements the ModelBranch interface.
 */
export function instanceOfModelBranch(value: object): value is ModelBranch {
    return true;
}

export function ModelBranchFromJSON(json: any): ModelBranch {
    return ModelBranchFromJSONTyped(json, false);
}

export function ModelBranchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelBranch {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'employees': json['employees'] == null ? undefined : ((json['employees'] as Array<any>).map(ModelEmployeeFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(ModelRoleFromJSON)),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'workSchedule': json['work_schedule'] == null ? undefined : ModelWorkScheduleFromJSON(json['work_schedule']),
    };
}

export function ModelBranchToJSON(json: any): ModelBranch {
    return ModelBranchToJSONTyped(json, false);
}

export function ModelBranchToJSONTyped(value?: ModelBranch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'company_id': value['companyId'],
        'created_at': value['createdAt'],
        'employees': value['employees'] == null ? undefined : ((value['employees'] as Array<any>).map(ModelEmployeeToJSON)),
        'name': value['name'],
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(ModelRoleToJSON)),
        'updated_at': value['updatedAt'],
        'uuid': value['uuid'],
        'work_schedule': ModelWorkScheduleToJSON(value['workSchedule']),
    };
}

