/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelUser } from './ModelUser';
import {
    ModelUserFromJSON,
    ModelUserFromJSONTyped,
    ModelUserToJSON,
    ModelUserToJSONTyped,
} from './ModelUser';

/**
 * 
 * @export
 * @interface ModelSession
 */
export interface ModelSession {
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    expiresAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    ipAddress?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelSession
     */
    isRevoked?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    refreshToken?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    userAgent?: string;
    /**
     * 
     * @type {Array<ModelUser>}
     * @memberof ModelSession
     */
    users?: Array<ModelUser>;
    /**
     * 
     * @type {string}
     * @memberof ModelSession
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ModelSession interface.
 */
export function instanceOfModelSession(value: object): value is ModelSession {
    return true;
}

export function ModelSessionFromJSON(json: any): ModelSession {
    return ModelSessionFromJSONTyped(json, false);
}

export function ModelSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelSession {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'ipAddress': json['ip_address'] == null ? undefined : json['ip_address'],
        'isRevoked': json['is_revoked'] == null ? undefined : json['is_revoked'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userAgent': json['user_agent'] == null ? undefined : json['user_agent'],
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(ModelUserFromJSON)),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ModelSessionToJSON(json: any): ModelSession {
    return ModelSessionToJSONTyped(json, false);
}

export function ModelSessionToJSONTyped(value?: ModelSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'expires_at': value['expiresAt'],
        'ip_address': value['ipAddress'],
        'is_revoked': value['isRevoked'],
        'refresh_token': value['refreshToken'],
        'updated_at': value['updatedAt'],
        'user_agent': value['userAgent'],
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(ModelUserToJSON)),
        'uuid': value['uuid'],
    };
}

