/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelUser } from './ModelUser';
import {
    ModelUserFromJSON,
    ModelUserFromJSONTyped,
    ModelUserToJSON,
    ModelUserToJSONTyped,
} from './ModelUser';

/**
 * 
 * @export
 * @interface ModelAttendance
 */
export interface ModelAttendance {
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    checkIn?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    checkOut?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    updatedAt?: string;
    /**
     * 
     * @type {Array<ModelUser>}
     * @memberof ModelAttendance
     */
    users?: Array<ModelUser>;
    /**
     * 
     * @type {string}
     * @memberof ModelAttendance
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ModelAttendance interface.
 */
export function instanceOfModelAttendance(value: object): value is ModelAttendance {
    return true;
}

export function ModelAttendanceFromJSON(json: any): ModelAttendance {
    return ModelAttendanceFromJSONTyped(json, false);
}

export function ModelAttendanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelAttendance {
    if (json == null) {
        return json;
    }
    return {
        
        'checkIn': json['check_in'] == null ? undefined : json['check_in'],
        'checkOut': json['check_out'] == null ? undefined : json['check_out'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'date': json['date'] == null ? undefined : json['date'],
        'location': json['location'] == null ? undefined : json['location'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(ModelUserFromJSON)),
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ModelAttendanceToJSON(json: any): ModelAttendance {
    return ModelAttendanceToJSONTyped(json, false);
}

export function ModelAttendanceToJSONTyped(value?: ModelAttendance | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'check_in': value['checkIn'],
        'check_out': value['checkOut'],
        'created_at': value['createdAt'],
        'date': value['date'],
        'location': value['location'],
        'status': value['status'],
        'updated_at': value['updatedAt'],
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(ModelUserToJSON)),
        'uuid': value['uuid'],
    };
}

