/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelRole
 */
export interface ModelRole {
    /**
     * 
     * @type {number}
     * @memberof ModelRole
     */
    branchId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelRole
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelRole
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelRole
     */
    updatedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelRole
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelRole
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ModelRole interface.
 */
export function instanceOfModelRole(value: object): value is ModelRole {
    return true;
}

export function ModelRoleFromJSON(json: any): ModelRole {
    return ModelRoleFromJSONTyped(json, false);
}

export function ModelRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelRole {
    if (json == null) {
        return json;
    }
    return {
        
        'branchId': json['branch_id'] == null ? undefined : json['branch_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'name': json['name'] == null ? undefined : json['name'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ModelRoleToJSON(json: any): ModelRole {
    return ModelRoleToJSONTyped(json, false);
}

export function ModelRoleToJSONTyped(value?: ModelRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch_id': value['branchId'],
        'created_at': value['createdAt'],
        'name': value['name'],
        'updated_at': value['updatedAt'],
        'user_id': value['userId'],
        'uuid': value['uuid'],
    };
}

