/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelLog
 */
export interface ModelLog {
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    executionTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    method?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    remoteAddr?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelLog
     */
    size?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelLog
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    userAgent?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelLog
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ModelLog interface.
 */
export function instanceOfModelLog(value: object): value is ModelLog {
    return true;
}

export function ModelLogFromJSON(json: any): ModelLog {
    return ModelLogFromJSONTyped(json, false);
}

export function ModelLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelLog {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'] == null ? undefined : json['action'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'email': json['email'] == null ? undefined : json['email'],
        'executionTime': json['executionTime'] == null ? undefined : json['executionTime'],
        'method': json['method'] == null ? undefined : json['method'],
        'path': json['path'] == null ? undefined : json['path'],
        'remoteAddr': json['remoteAddr'] == null ? undefined : json['remoteAddr'],
        'size': json['size'] == null ? undefined : json['size'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'userAgent': json['userAgent'] == null ? undefined : json['userAgent'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ModelLogToJSON(json: any): ModelLog {
    return ModelLogToJSONTyped(json, false);
}

export function ModelLogToJSONTyped(value?: ModelLog | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'created_at': value['createdAt'],
        'email': value['email'],
        'executionTime': value['executionTime'],
        'method': value['method'],
        'path': value['path'],
        'remoteAddr': value['remoteAddr'],
        'size': value['size'],
        'status': value['status'],
        'updated_at': value['updatedAt'],
        'userAgent': value['userAgent'],
        'uuid': value['uuid'],
    };
}

