/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelCompanyOption
 */
export interface ModelCompanyOption {
    /**
     * 
     * @type {string}
     * @memberof ModelCompanyOption
     */
    checkInTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCompanyOption
     */
    checkOutTime?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelCompanyOption
     */
    companyId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelCompanyOption
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCompanyOption
     */
    updatedAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelCompanyOption
     */
    useCheckout?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelCompanyOption
     */
    uuid?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelCompanyOption
     */
    workingHours?: number;
}

/**
 * Check if a given object implements the ModelCompanyOption interface.
 */
export function instanceOfModelCompanyOption(value: object): value is ModelCompanyOption {
    return true;
}

export function ModelCompanyOptionFromJSON(json: any): ModelCompanyOption {
    return ModelCompanyOptionFromJSONTyped(json, false);
}

export function ModelCompanyOptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelCompanyOption {
    if (json == null) {
        return json;
    }
    return {
        
        'checkInTime': json['check_in_time'] == null ? undefined : json['check_in_time'],
        'checkOutTime': json['check_out_time'] == null ? undefined : json['check_out_time'],
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'useCheckout': json['use_checkout'] == null ? undefined : json['use_checkout'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'workingHours': json['workingHours'] == null ? undefined : json['workingHours'],
    };
}

export function ModelCompanyOptionToJSON(json: any): ModelCompanyOption {
    return ModelCompanyOptionToJSONTyped(json, false);
}

export function ModelCompanyOptionToJSONTyped(value?: ModelCompanyOption | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'check_in_time': value['checkInTime'],
        'check_out_time': value['checkOutTime'],
        'company_id': value['companyId'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'use_checkout': value['useCheckout'],
        'uuid': value['uuid'],
        'workingHours': value['workingHours'],
    };
}

