/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelAttendance } from './ModelAttendance';
import {
    ModelAttendanceFromJSON,
    ModelAttendanceFromJSONTyped,
    ModelAttendanceToJSON,
    ModelAttendanceToJSONTyped,
} from './ModelAttendance';
import type { ModelCompany } from './ModelCompany';
import {
    ModelCompanyFromJSON,
    ModelCompanyFromJSONTyped,
    ModelCompanyToJSON,
    ModelCompanyToJSONTyped,
} from './ModelCompany';
import type { ModelQRCode } from './ModelQRCode';
import {
    ModelQRCodeFromJSON,
    ModelQRCodeFromJSONTyped,
    ModelQRCodeToJSON,
    ModelQRCodeToJSONTyped,
} from './ModelQRCode';
import type { ModelPermission } from './ModelPermission';
import {
    ModelPermissionFromJSON,
    ModelPermissionFromJSONTyped,
    ModelPermissionToJSON,
    ModelPermissionToJSONTyped,
} from './ModelPermission';
import type { ModelEmployee } from './ModelEmployee';
import {
    ModelEmployeeFromJSON,
    ModelEmployeeFromJSONTyped,
    ModelEmployeeToJSON,
    ModelEmployeeToJSONTyped,
} from './ModelEmployee';
import type { ModelSession } from './ModelSession';
import {
    ModelSessionFromJSON,
    ModelSessionFromJSONTyped,
    ModelSessionToJSON,
    ModelSessionToJSONTyped,
} from './ModelSession';
import type { ModelLog } from './ModelLog';
import {
    ModelLogFromJSON,
    ModelLogFromJSONTyped,
    ModelLogToJSON,
    ModelLogToJSONTyped,
} from './ModelLog';

/**
 * 
 * @export
 * @interface ModelUser
 */
export interface ModelUser {
    /**
     * 
     * @type {Array<ModelAttendance>}
     * @memberof ModelUser
     */
    attendances?: Array<ModelAttendance>;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    authProvider?: string;
    /**
     * 
     * @type {Array<ModelCompany>}
     * @memberof ModelUser
     */
    company?: Array<ModelCompany>;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    email?: string;
    /**
     * 
     * @type {ModelEmployee}
     * @memberof ModelUser
     */
    employee?: ModelEmployee;
    /**
     * 
     * @type {boolean}
     * @memberof ModelUser
     */
    isEmailVerified?: boolean;
    /**
     * 
     * @type {ModelLog}
     * @memberof ModelUser
     */
    log?: ModelLog;
    /**
     * 
     * @type {Array<ModelPermission>}
     * @memberof ModelUser
     */
    permissions?: Array<ModelPermission>;
    /**
     * 
     * @type {ModelQRCode}
     * @memberof ModelUser
     */
    qrcode?: ModelQRCode;
    /**
     * admin, owner, employee
     * @type {string}
     * @memberof ModelUser
     */
    role?: string;
    /**
     * 
     * @type {Array<ModelSession>}
     * @memberof ModelUser
     */
    sessions?: Array<ModelSession>;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelUser
     */
    uuid?: string;
}

/**
 * Check if a given object implements the ModelUser interface.
 */
export function instanceOfModelUser(value: object): value is ModelUser {
    return true;
}

export function ModelUserFromJSON(json: any): ModelUser {
    return ModelUserFromJSONTyped(json, false);
}

export function ModelUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelUser {
    if (json == null) {
        return json;
    }
    return {
        
        'attendances': json['attendances'] == null ? undefined : ((json['attendances'] as Array<any>).map(ModelAttendanceFromJSON)),
        'authProvider': json['auth_provider'] == null ? undefined : json['auth_provider'],
        'company': json['company'] == null ? undefined : ((json['company'] as Array<any>).map(ModelCompanyFromJSON)),
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'email': json['email'] == null ? undefined : json['email'],
        'employee': json['employee'] == null ? undefined : ModelEmployeeFromJSON(json['employee']),
        'isEmailVerified': json['is_email_verified'] == null ? undefined : json['is_email_verified'],
        'log': json['log'] == null ? undefined : ModelLogFromJSON(json['log']),
        'permissions': json['permissions'] == null ? undefined : ((json['permissions'] as Array<any>).map(ModelPermissionFromJSON)),
        'qrcode': json['qrcode'] == null ? undefined : ModelQRCodeFromJSON(json['qrcode']),
        'role': json['role'] == null ? undefined : json['role'],
        'sessions': json['sessions'] == null ? undefined : ((json['sessions'] as Array<any>).map(ModelSessionFromJSON)),
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'username': json['username'] == null ? undefined : json['username'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function ModelUserToJSON(json: any): ModelUser {
    return ModelUserToJSONTyped(json, false);
}

export function ModelUserToJSONTyped(value?: ModelUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attendances': value['attendances'] == null ? undefined : ((value['attendances'] as Array<any>).map(ModelAttendanceToJSON)),
        'auth_provider': value['authProvider'],
        'company': value['company'] == null ? undefined : ((value['company'] as Array<any>).map(ModelCompanyToJSON)),
        'created_at': value['createdAt'],
        'email': value['email'],
        'employee': ModelEmployeeToJSON(value['employee']),
        'is_email_verified': value['isEmailVerified'],
        'log': ModelLogToJSON(value['log']),
        'permissions': value['permissions'] == null ? undefined : ((value['permissions'] as Array<any>).map(ModelPermissionToJSON)),
        'qrcode': ModelQRCodeToJSON(value['qrcode']),
        'role': value['role'],
        'sessions': value['sessions'] == null ? undefined : ((value['sessions'] as Array<any>).map(ModelSessionToJSON)),
        'updated_at': value['updatedAt'],
        'username': value['username'],
        'uuid': value['uuid'],
    };
}

