/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelCompanyOption } from './ModelCompanyOption';
import {
    ModelCompanyOptionFromJSON,
    ModelCompanyOptionFromJSONTyped,
    ModelCompanyOptionToJSON,
    ModelCompanyOptionToJSONTyped,
} from './ModelCompanyOption';
import type { ModelBranch } from './ModelBranch';
import {
    ModelBranchFromJSON,
    ModelBranchFromJSONTyped,
    ModelBranchToJSON,
    ModelBranchToJSONTyped,
} from './ModelBranch';
import type { ModelWorkSchedule } from './ModelWorkSchedule';
import {
    ModelWorkScheduleFromJSON,
    ModelWorkScheduleFromJSONTyped,
    ModelWorkScheduleToJSON,
    ModelWorkScheduleToJSONTyped,
} from './ModelWorkSchedule';

/**
 * 
 * @export
 * @interface ModelCompany
 */
export interface ModelCompany {
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    address?: string;
    /**
     * 
     * @type {Array<ModelBranch>}
     * @memberof ModelCompany
     */
    branches?: Array<ModelBranch>;
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    name?: string;
    /**
     * 
     * @type {ModelCompanyOption}
     * @memberof ModelCompany
     */
    options?: ModelCompanyOption;
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    ownerEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCompany
     */
    uuid?: string;
    /**
     * 
     * @type {ModelWorkSchedule}
     * @memberof ModelCompany
     */
    workSchedule?: ModelWorkSchedule;
}

/**
 * Check if a given object implements the ModelCompany interface.
 */
export function instanceOfModelCompany(value: object): value is ModelCompany {
    return true;
}

export function ModelCompanyFromJSON(json: any): ModelCompany {
    return ModelCompanyFromJSONTyped(json, false);
}

export function ModelCompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelCompany {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'branches': json['branches'] == null ? undefined : ((json['branches'] as Array<any>).map(ModelBranchFromJSON)),
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'name': json['name'] == null ? undefined : json['name'],
        'options': json['options'] == null ? undefined : ModelCompanyOptionFromJSON(json['options']),
        'ownerEmail': json['owner_email'] == null ? undefined : json['owner_email'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'workSchedule': json['work_schedule'] == null ? undefined : ModelWorkScheduleFromJSON(json['work_schedule']),
    };
}

export function ModelCompanyToJSON(json: any): ModelCompany {
    return ModelCompanyToJSONTyped(json, false);
}

export function ModelCompanyToJSONTyped(value?: ModelCompany | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'branches': value['branches'] == null ? undefined : ((value['branches'] as Array<any>).map(ModelBranchToJSON)),
        'created_at': value['createdAt'],
        'name': value['name'],
        'options': ModelCompanyOptionToJSON(value['options']),
        'owner_email': value['ownerEmail'],
        'updated_at': value['updatedAt'],
        'uuid': value['uuid'],
        'work_schedule': ModelWorkScheduleToJSON(value['workSchedule']),
    };
}

