/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelWorkSchedule
 */
export interface ModelWorkSchedule {
    /**
     * 
     * @type {number}
     * @memberof ModelWorkSchedule
     */
    branchId?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelWorkSchedule
     */
    companyId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelWorkSchedule
     */
    employeeId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    endTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelWorkSchedule
     */
    workingDay?: string;
}

/**
 * Check if a given object implements the ModelWorkSchedule interface.
 */
export function instanceOfModelWorkSchedule(value: object): value is ModelWorkSchedule {
    return true;
}

export function ModelWorkScheduleFromJSON(json: any): ModelWorkSchedule {
    return ModelWorkScheduleFromJSONTyped(json, false);
}

export function ModelWorkScheduleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelWorkSchedule {
    if (json == null) {
        return json;
    }
    return {
        
        'branchId': json['branch_id'] == null ? undefined : json['branch_id'],
        'companyId': json['company_id'] == null ? undefined : json['company_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'employeeId': json['employee_id'] == null ? undefined : json['employee_id'],
        'endTime': json['end_time'] == null ? undefined : json['end_time'],
        'startTime': json['start_time'] == null ? undefined : json['start_time'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'workingDay': json['working_day'] == null ? undefined : json['working_day'],
    };
}

export function ModelWorkScheduleToJSON(json: any): ModelWorkSchedule {
    return ModelWorkScheduleToJSONTyped(json, false);
}

export function ModelWorkScheduleToJSONTyped(value?: ModelWorkSchedule | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch_id': value['branchId'],
        'company_id': value['companyId'],
        'created_at': value['createdAt'],
        'employee_id': value['employeeId'],
        'end_time': value['endTime'],
        'start_time': value['startTime'],
        'updated_at': value['updatedAt'],
        'uuid': value['uuid'],
        'working_day': value['workingDay'],
    };
}

