/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DtoCreateQrResponse } from './DtoCreateQrResponse';
import {
    DtoCreateQrResponseFromJSON,
    DtoCreateQrResponseFromJSONTyped,
    DtoCreateQrResponseToJSON,
    DtoCreateQrResponseToJSONTyped,
} from './DtoCreateQrResponse';

/**
 * 
 * @export
 * @interface QrcodeGet200Response
 */
export interface QrcodeGet200Response {
    /**
     * 
     * @type {DtoCreateQrResponse}
     * @memberof QrcodeGet200Response
     */
    data?: DtoCreateQrResponse;
    /**
     * 
     * @type {string}
     * @memberof QrcodeGet200Response
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof QrcodeGet200Response
     */
    status?: number;
}

/**
 * Check if a given object implements the QrcodeGet200Response interface.
 */
export function instanceOfQrcodeGet200Response(value: object): value is QrcodeGet200Response {
    return true;
}

export function QrcodeGet200ResponseFromJSON(json: any): QrcodeGet200Response {
    return QrcodeGet200ResponseFromJSONTyped(json, false);
}

export function QrcodeGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QrcodeGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : DtoCreateQrResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function QrcodeGet200ResponseToJSON(json: any): QrcodeGet200Response {
    return QrcodeGet200ResponseToJSONTyped(json, false);
}

export function QrcodeGet200ResponseToJSONTyped(value?: QrcodeGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': DtoCreateQrResponseToJSON(value['data']),
        'message': value['message'],
        'status': value['status'],
    };
}

