/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesResponse
 */
export interface TypesResponse {
    /**
     * 
     * @type {object}
     * @memberof TypesResponse
     */
    data?: object;
    /**
     * 
     * @type {string}
     * @memberof TypesResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof TypesResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the TypesResponse interface.
 */
export function instanceOfTypesResponse(value: object): value is TypesResponse {
    return true;
}

export function TypesResponseFromJSON(json: any): TypesResponse {
    return TypesResponseFromJSONTyped(json, false);
}

export function TypesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesResponseToJSON(json: any): TypesResponse {
    return TypesResponseToJSONTyped(json, false);
}

export function TypesResponseToJSONTyped(value?: TypesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'message': value['message'],
        'status': value['status'],
    };
}

