/* tslint:disable */
/* eslint-disable */
/**
 * Growy API
 * Growy API
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: ilham15suandi@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TypesErrorResponse
 */
export interface TypesErrorResponse {
    /**
     * 
     * @type {object}
     * @memberof TypesErrorResponse
     */
    error?: object;
    /**
     * 
     * @type {string}
     * @memberof TypesErrorResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof TypesErrorResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the TypesErrorResponse interface.
 */
export function instanceOfTypesErrorResponse(value: object): value is TypesErrorResponse {
    return true;
}

export function TypesErrorResponseFromJSON(json: any): TypesErrorResponse {
    return TypesErrorResponseFromJSONTyped(json, false);
}

export function TypesErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'] == null ? undefined : json['error'],
        'message': json['message'] == null ? undefined : json['message'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function TypesErrorResponseToJSON(json: any): TypesErrorResponse {
    return TypesErrorResponseToJSONTyped(json, false);
}

export function TypesErrorResponseToJSONTyped(value?: TypesErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
        'message': value['message'],
        'status': value['status'],
    };
}

